name: ci

on:
  push:

jobs:
  buildx:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build Auth
        run: |
          cd auth
          docker build . -t auth:1.0
      -
        name: Build Jobs
        run: |
          cd jobs
          docker build . -t jobs:1.0
  deploy:
    name: Nomad Deploy
    runs-on: ubuntu-latest
    needs: buildx
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy Auth
        uses: qazz92/nomad-deploy-action@1.0.1
        with:
          token: ${{ secrets.YOUR_NOMAD_SECRET }}
          address: ${{ secrets.YOUR_NOMAD_SERVER }}
          job: auth/app.hcl
        
      - name: Deploy Jobs
        uses: qazz92/nomad-deploy-action@1.0.1
        with:
          token: ${{ secrets.YOUR_NOMAD_SECRET }}
          address: ${{ secrets.YOUR_NOMAD_SERVER }}
          job: jobs/app.hcl